# Generated by Django 2.1.5 on 2023-08-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangoAppName', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('news_article_id', models.IntegerField()),
                ('s1_cnn_original', models.FloatField()),
                ('s1_adam', models.FloatField()),
                ('s1_xsum', models.FloatField()),
                ('s2_cnn_original', models.FloatField()),
                ('s2_adam', models.FloatField()),
                ('s2_xsum', models.FloatField()),
                ('s3_cnn_original', models.FloatField()),
                ('s3_adam', models.FloatField()),
                ('s3_xsum', models.FloatField()),
                ('s4_cnn_original', models.FloatField()),
                ('s4_adam', models.FloatField()),
                ('s4_xsum', models.FloatField()),
                ('cnn_original_rank', models.IntegerField()),
                ('xsum_rank', models.IntegerField()),
                ('adam_rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
